import Head from 'next/head'
import Feed from '../components/Feed/Feed'
import Header from '../components/Header/Header'

export default function Home() {
  return (
    // div className={styles.container}
    <div className="bg-gray-50 h-screen overflow-y-scroll scrollbar-hide">
      <Head>
        <title>MUNIN</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* header */}
          <Header/>
          
      {/* feed */}
          <Feed />
      {/* modal */}

    </div>
  )
}
